services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 9999:80
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
  ollama:
    volumes:
      - $HOME/.ollama:/root/.ollama
    # container_name: ollama
    # pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    ports:
      - 21434:11434
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
# volumes:
#   ollama-data: